export { Header } from './Header/Header'
export { Hero } from './Hero/Hero'
export { Steps } from './Steps/Steps'
export { Catalog } from './Catalog/Catalog'
export { Pricing } from './Pricing/Pricing'
export { Reviews } from './Reviews/Reviews'
export { Footer } from './Footer/Footer'
